### ISSUE TITLE
Question: language is Chinese

### ISSUE THREAD

**Issue by poeeain** [Lin-jun-xiang/docGPT-streamlit#11]
### Issue you'd like to raise.

The default language is Chinese?
I use the default model.
Whenever I ask, it answers me in Chinese. Is there any option to change to English by default. Thanks in advance.

**Comment by Lin-jun-xiang** [comment]
@poeeain 

Thanks your report.

The `gpt4free` will use **reverse-engineering** skill to call models which also called `providers`.
Some `providers` are fine tuned by Chinese, that's why u got Chinese results.
You can try to use the prompt as following (**answer with english**):

```
Give me the solution of two sum through python code, answer with english:
```
