### ISSUE TITLE
試了很多provider 只有chatbase能用

### ISSUE THREAD

**Issue by murdonson** [Lin-jun-xiang/docGPT-streamlit#8]

**Comment by Lin-jun-xiang** [comment]
@murdonson 

需要將 `g4f` 進行更新: `pip install -U g4f`。

另外，`g4f` 會定期更新可使用的 Provider 列表，可參考此[連結](https://github.com/xtekky/gpt4free?tab=readme-ov-file#gpt-35)。

**Comment by murdonson** [comment]
可以支持對word文檔裡面表格數據進行分析嗎，比如問平均體重類似的問題？

**Comment by murdonson** [comment]
這個項目可以私有化部署嗎 感覺你這些provider都是聯網後使用

**Comment by Lin-jun-xiang** [comment]
> 可以支持對word文檔裡面表格數據進行分析嗎，比如問平均體重類似的問題？

這個部分需要研究一下，對於 PDF 文檔的部分我比較清楚，最暴力的方法就是將 word 文檔轉成 PDF，然後用 `pdfplumberloader` 去解析，這個解析器可以比較正確的處理表格內容。

**Comment by Lin-jun-xiang** [comment]
> 這個項目可以私有化部署嗎 感覺你這些provider都是聯網後使用

provider 逆向其他平台的 openai api，因此勢必得聯網，無法私有化部屬。 (純屬娛樂的項目!)
